FROM confluentinc/cp-kafka-connect-base:6.1.4

ENV CONNECT_PLUGIN_PATH="/usr/share/java,/usr/share/confluent-hub-components,/data/connect-jars"

# For generating random data from an Avro schema
RUN confluent-hub install --no-prompt confluentinc/kafka-connect-datagen:0.4.0

# For the mongodb sink exercise
RUN confluent-hub install --no-prompt mongodb/kafka-connect-mongodb:latest