spring:
  kafka:
    bootstrap-servers: "localhost:9092,localhost:9093,localhost:9094"

#   This section is commented out because we now do this config in code (PeopleProducerConfig class)

#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

topics:
  people-basic:
    name: "people.basic.java"
    partitions: 3
    replicas: 3
