server:
  port: 8088

spring:
  kafka:
    bootstrap-servers: "localhost:9092,localhost:9093,localhost:9094"

topics:
  people-basic:
    name: "people.basic.java"
  people-advanced:
    name: "people.advanced.java"
