# curl -H "Content-Type: application/json" -d "{\"count\":3}" -X POST http://127.0.0.1:8000/api/people
POST http://127.0.0.1:8000/api/people
Content-Type: application/json
Accept: application/json

{
  "count": 100000
}